# Welcome to my numpy tutorial

In [1]:
import numpy as np

In [18]:
myarr = np.array([[3,5,32,7]], np.int8)

In [19]:
myarr[0,1]

np.int8(5)

In [20]:
myarr[0,1]=45

In [21]:
myarr

array([[ 3, 45, 32,  7]], dtype=int8)

In [22]:
myarr.shape

(1, 4)

In [23]:
myarr.dtype

dtype('int8')

# Array creation : Conversion from other python structers

In [24]:
listarray = np.array([[0,1,2],[6,4,5],[7,8,9,]])

In [25]:
listarray

array([[0, 1, 2],
       [6, 4, 5],
       [7, 8, 9]])

In [26]:
listarray.shape

(3, 3)

In [27]:
listarray.size

9

In [28]:
listarray.dtype

dtype('int64')

In [29]:
np.array({34,25,30})

array({25, 34, 30}, dtype=object)

In [30]:
zeros = np.zeros((2,6))

In [31]:
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
zeros.dtype

dtype('float64')

In [33]:
zeros.shape

(2, 6)

In [34]:
zeros.size

12

In [35]:
rng = np.arange(15)

In [36]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
lspace = np.linspace(1,5,15)

In [38]:
lspace

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [39]:
emp = np.empty((2,6))

In [40]:
emp

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [41]:
emp_like = np.empty_like(lspace)

In [42]:
emp_like

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

In [43]:
ide = np.identity(45)

In [44]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [45]:
ide.shape

(45, 45)

In [46]:
ide.size

2025

In [47]:
arr = np.arange(100)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [49]:
arr.reshape(5,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [50]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [51]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [52]:
arr = np.array(x)

In [53]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [54]:

arr.sum(axis=0)

array([12,  8,  9])

In [55]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [56]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [57]:
arr.size

9

In [58]:
arr.nbytes

72

In [59]:
one = np.array([1,3,5,213,60])

In [60]:
one.argmax()

np.int64(3)

In [61]:
one.argmin()

np.int64(0)

In [62]:
one.argsort()

array([0, 1, 2, 4, 3])

In [63]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [64]:
arr.argmax(axis=0)

array([2, 1, 1])

In [65]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
arr2=([[1,2,3],
       [7,5,6],
       [10,11,12]])

In [67]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [68]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [69]:
np.where(arr>5)

(array([1, 2]), array([2, 0]))

In [70]:
np.count_nonzero(arr)

np.int64(8)

In [71]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [72]:
import sys

In [73]:
py_arr = [0,4,55,3]

In [74]:
np_arr = np.array(py_arr)

In [75]:
sys.getsizeof

<function sys.getsizeof>

# PRACTICE 

In [76]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [77]:
arr2=np.array([[10,11,12],
              [13,14,15],
              [16,17,18]])

In [78]:
print(arr+arr2)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [79]:
arr.shape

(3, 3)

In [80]:
a=([1,2,3,4])
b=([[10,20],[30,40]])
print(a+b)

[1, 2, 3, 4, [10, 20], [30, 40]]


In [81]:
print(a)

[1, 2, 3, 4]


In [82]:
print(b)

[[10, 20], [30, 40]]


In [83]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[0])
print(arr[1:5])
print(arr+10)
print(arr*5)
print(arr.mean())
print(arr.max())
print(arr.min())

1
[2 3 4 5]
[11 12 13 14 15 16 17 18]
[ 5 10 15 20 25 30 35 40]
4.5
8
1


In [84]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
x = np.array([1,2,3])
w = np.array([0.5, 1.5, -1])

y_pred = np.dot(x, w)
print(y_pred)


0.5


In [86]:
x = ([1,2,3,4,5])
y = ([2,6,7,8,9])

w =2
# y_pred =x*w
y_pred=y*w
print(y_pred)

[2, 6, 7, 8, 9, 2, 6, 7, 8, 9]


In [87]:
x = np.array([1,2,3,4,5])
y = np.array([2,4,6,8,10])

w = 2
y_pred = x * w

error = y - y_pred
print(error)
mse=np.mean(error**2)
print(mse)

[0 0 0 0 0]
0.0


In [88]:
a=np.arange(1,100000)
#slow way in numpy
%timeit [x*2 for x in a]
#fast way in numpy
%timeit a*2

20.4 ms ± 2.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
131 μs ± 2.78 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [89]:
a = np.array([10, 20, 30, 40, 50])

print(a[a > 25])   # Boolean masking


[30 40 50]


In [90]:
a=np.array([10,20,40,60,70])
mask=a>21
print(mask)
print(a[mask])

[False False  True  True  True]
[40 60 70]


In [91]:
scores=np.array([11,14,15,16,18,19])

passed=scores[scores>13]
print(passed)

[14 15 16 18 19]


In [92]:
a=np.array([11,13,15,19,20])
print(a[(a>10)&(a<19.5)])

[11 13 15 19]


In [93]:
a=np.array([111,113,400,500,221,600])
idx=[0,2,3]
print(a[idx])

[111 400 500]


In [94]:
a=np.array([11,12,13,14,15,16])
result=np.where(a>12,"high","low")
print(result)

['low' 'low' 'high' 'high' 'high' 'high']


In [95]:
scores = np.array([45, 72, 88, 33])

status = np.where(scores >= 60, "PASS", "FAIL")
print(status)


['FAIL' 'PASS' 'PASS' 'FAIL']


In [96]:
print(type(result))

<class 'numpy.ndarray'>


In [97]:
scores.shape

(4,)

In [98]:
scores.size

4

In [99]:
temp=np.array([40,45,42,44,46])
task=np.where(temp>42,"hot","cold")
print(task)

['cold' 'hot' 'cold' 'hot' 'hot']


In [100]:
marks=np.array([45,55,50,46,47])
task=np.where(marks>45,"pass","fail")
print(task)

['fail' 'pass' 'pass' 'pass' 'pass']


In [101]:
a=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
b=np.array([11,12,13])
print(a+b)
print(a*b)
print(a**b)

[[12 14 16]
 [15 17 19]
 [18 20 22]]
[[ 11  24  39]
 [ 44  60  78]
 [ 77  96 117]]
[[            1          4096       1594323]
 [      4194304     244140625   13060694016]
 [   1977326743   68719476736 2541865828329]]


In [102]:
a = np.array([10,20,30])
b =np.array([[11],
             [12],
            [13]])
print(a+b)

[[21 31 41]
 [22 32 42]
 [23 33 43]]


In [103]:
x=np.array([11,16,15,17,20])
w=np.array([[13],
  [15],
   [22]])
print(x*w)

[[143 208 195 221 260]
 [165 240 225 255 300]
 [242 352 330 374 440]]


In [104]:
a=np.array([11,12,13,14,15,16])
print(a.shape)
b= a.reshape(2,3)
print(b)

(6,)
[[11 12 13]
 [14 15 16]]


In [105]:
a=np.array([[11,12,13],
            [15,16,17]])
print(a.sum(axis=0)) #columns ka sum ko define kare
print(a.sum(axis=1)) #rows ka sum  ko define kare

[26 28 30]
[36 48]


In [111]:
k=([1,25,49,221,64])
print(np.sqrt(k))  #square root
print(np.log(k))   #log
print(np.exp(k))   #e¹ ≈ 2.718,e⁴ ≈ 54.598

[ 1.          5.          7.         14.86606875  8.        ]
[0.         3.21887582 3.8918203  5.3981627  4.15888308]
[2.71828183e+00 7.20048993e+10 1.90734657e+21 9.52972790e+95
 6.23514908e+27]


In [7]:
k =np.array([[1,2,3],
             [4,5,6]])
print(np.sum(k))
print(np.sum(k,axis=0))
print(np.sum(k,axis=1))

21
[5 7 9]
[ 6 15]


In [11]:
k= np.arange(11,17)
print(k.reshape(2,3))
print(k.reshape(3,2))

[[11 12 13]
 [14 15 16]]
[[11 12]
 [13 14]
 [15 16]]


In [26]:
k=np.arange(25,76)
print(k)
print(k.reshape(17,3))

[25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75]
[[25 26 27]
 [28 29 30]
 [31 32 33]
 [34 35 36]
 [37 38 39]
 [40 41 42]
 [43 44 45]
 [46 47 48]
 [49 50 51]
 [52 53 54]
 [55 56 57]
 [58 59 60]
 [61 62 63]
 [64 65 66]
 [67 68 69]
 [70 71 72]
 [73 74 75]]


In [28]:
M=np.array([[21,22,23],
            [24,25,26]])
print(M.flatten())

[21 22 23 24 25 26]


In [31]:
K=np.array([[1,2],
            [4,5],
            [7,8]])
M=np.array([[11,12,13],
             [14,15,16]])
print(np.dot(K,M))

[[ 39  42  45]
 [114 123 132]
 [189 204 219]]


In [33]:
a=np.array([[1,2,3],
           [4,5,6],
            [7,8,9]])

b=np.array([[11,12,13],
           [14,15,16],
           [14,15,16]])
print(np.dot(a,b))

[[ 81  87  93]
 [198 213 228]
 [315 339 363]]


In [34]:
print(a@b) # simple way output

[[ 81  87  93]
 [198 213 228]
 [315 339 363]]


In [35]:
a=np.array([[1],[2],[3]])
b=np.array([[4,5,6]])
print(a+b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [39]:
a=np.array([[11,12,13],
            [14,15,16],
            [17,18,19]])
b=np.array([[21,22,23],
           [24,25,26],
           [27,28,29]])
print(a+b)

[[32 34 36]
 [38 40 42]
 [44 46 48]]


In [40]:
a=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])
b=np.array([[11,12,13],
            [14,15,16],
            [18,17,19]])
print(np.concatenate([a,b]))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [18 17 19]]


In [41]:
print(np.vstack([a,b]))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [18 17 19]]


In [42]:
print(np.hstack([a,b]))

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 18 17 19]]
